name: p
description: A Flutter event management application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  path: ^1.8.3
  
  share_plus: ^7.2.1
  crypto: ^3.0.3        # For password hashing
  image_picker: ^1.0.4  # For profile photos
  mailer: ^6.0.1  
  # Date formatting
  intl: ^0.19.0
  
  # UI
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true